apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: outstanding-rhinoceros-nodejs 
  janus-idp.io/tekton: outstanding-rhinoceros-nodejs
  backstage.io/kubernetes-id: outstanding-rhinoceros-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: outstanding-rhinoceros-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  