apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: outstanding-rhinoceros-nodejs-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/outstanding-rhinoceros-nodejs