apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: outstanding-rhinoceros-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: outstanding-rhinoceros-nodejs 
  name: outstanding-rhinoceros-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: outstanding-rhinoceros-nodejs 
